AppNetCodeCapas6/Controllers/LaboratorioController.cs
using CapaDatos;
using CapaEntidad;
using CapaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace AppNetCodeCapas6.Controllers
{
    public class LaboratorioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public List<LaboratorioCLS> listarLaboratorio()
        {
            LaboratorioBL obj = new LaboratorioBL();
            return obj.listarLaboratorio();
        }
        public List<LaboratorioCLS> filtrarLaboratorio(LaboratorioCLS objLab)
        {
            LaboratorioDAL obj = new LaboratorioDAL();
            return obj.filtrarLaboratorio(objLab);
        }

        // 1 (correcto) y 0 (incorrecto)
        public int guardarDatos(LaboratorioCLS oLaboratorio)
        {
            LaboratorioDAL obj = new LaboratorioDAL();
            return obj.guardarLaboratorio(oLaboratorio);
        }

        public LaboratorioCLS recuperarLaboratorio(int id)
        {
            LaboratorioDAL obj = new LaboratorioDAL();
            return obj.recuperarLaboratorio(id);
        }

        public int eliminarLaboratorio(int id)
        {
            LaboratorioDAL obj = new LaboratorioDAL();
            return obj.eliminarLaboratorio(id);
        }
    }
}

AppNetCodeCapas6/Controllers/MedicamentoController.cs
using CapaEntidad;
using CapaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace AppNetCodeCapas6.Controllers
{
    public class MedicamentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<MedicamentoCLS> listarMedicamento()
        {
            MedicamentoBL oMedicamentoBL = new MedicamentoBL();
            return oMedicamentoBL.listarMedicamento();
        }

        public MedicamentoComboCLS listarCombosMedicamento()
        {
            MedicamentoBL oMedicamentoBL = new MedicamentoBL();
            return oMedicamentoBL.listarCombosMedicamento();
        }

        public List<MedicamentoCLS> filtrarMedicamento(MedicamentoCLS obj)
        {
            MedicamentoBL oMedicamentoBL = new MedicamentoBL();
            return oMedicamentoBL.filtrarMedicamento(obj);
        }

        public MedicamentoCLS recuperarMedicamento(int iidmedicamento)
        {
            MedicamentoBL oMedicamentoBL = new MedicamentoBL();
            return oMedicamentoBL.recuperarMedicamento(iidmedicamento);
        }

        public int guardarMedicamento(MedicamentoCLS oMedicamentoCLS)
        {
            MedicamentoBL oMedicamentoBL = new MedicamentoBL();
            return oMedicamentoBL.guardarMedicamento(oMedicamentoCLS);
        }

        public int eliminarMedicamento(int id)
        {
            MedicamentoBL oMedicamentoBL = new MedicamentoBL();
            return oMedicamentoBL.eliminarMedicamento(id);
        }
    }
}

AppNetCodeCapas6/Controllers/PersonaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.Extensions.Configuration;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CapaNegocio;
using CapaEntidad;
using System.IO;
namespace AppNetCodeCapas6.Controllers
{
    public class PersonaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<PersonaCLS> listarPersona()
        {
            PersonaBL oPersonaBL = new PersonaBL();
            return oPersonaBL.listarPersona();
        }

        public List<PersonaCLS> filtrarPersona(PersonaCLS oPersonaCLS)
        {
            PersonaBL oPersonaBL = new PersonaBL();
            return oPersonaBL.filtrarPersona(oPersonaCLS);
        }
    }
}

AppNetCodeCapas6/Controllers/SucursalController.cs
using CapaEntidad;
using CapaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace AppNetCodeCapas6.Controllers
{
    public class SucursalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        // Metodo para comunicarse con la Capa de Negocio
        public List<SucursalCLS> listarSucursal()
        {
            SucursalBL obj = new SucursalBL();
            return obj.listarSucursal();
        }

        public List<SucursalCLS> filtrarSucursal(string nombreSucursal)
        {
            SucursalBL obj = new SucursalBL();
            return obj.filtrarSucursal(nombreSucursal);
        }

        public int GuardarDatos(SucursalCLS oSucursalCLS, IFormFile fotoEnviar)
        {
            //IFormFile a byte[]
            byte[] buffer = null;
            string nombreFoto = "";
            if (fotoEnviar != null)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    fotoEnviar.CopyTo(ms);
                    nombreFoto = fotoEnviar.FileName;
                    //Array de Bytes
                    buffer = ms.ToArray();
                    oSucursalCLS.foto = buffer;
                    oSucursalCLS.nombrefoto = nombreFoto;
                }
            }
            SucursalBL obj = new SucursalBL();
            return obj.guardarSucursal(oSucursalCLS);
        }

        public SucursalCLS recuperarSucursal(int iidsucursal)
        {
            SucursalBL obj = new SucursalBL();
            return obj.recuperarSucursal(iidsucursal);
        }
    }
}

AppNetCodeCapas6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppNetCodeCapas6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppNetCodeCapas6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppNetCodeCapas6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoMedicamento" asp-action="Index">Tipo Medicamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sucursal" asp-action="Index">Sucursal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Laboratorio" asp-action="Index">Laboratorio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicamento" asp-action="Index">Medicamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoAdministracion" asp-action="Index">Tipo Administracion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoUsuario" asp-action="Index">Tipo usuario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persona" asp-action="Index">Persona</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <input type="hidden" id="hdfOculto" value='@Url.Content("~")'/>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppNetCodeCapas6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <div id="divLoading" style="display:none;
                                background-image:url(../img/Spinner-1s-200px.svg);
                                position:absolute;
                                top:0;
                                left:0;
                                width:100%;
                                height:100%;
                                background-repeat:no-repeat;
                                background-position:center;">
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>