AppNetCodeCapas6/Controllers/TipoMedicamentoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.Extensions.Configuration;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CapaNegocio;
using CapaEntidad;
using System.IO;

namespace MiPrimeraAppNetCoreCapas6.Controllers
{
    public class TipoMedicamentoController : Controller
    {
        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Inicio()
        {
            return View();
        }
        public IActionResult SinMenu()
        {
            return View();
        }
        //string
        public string saludo()
        {
            return "Hola amigos";
        }
        public string saludoNombre(string nombre)
        {
            return "Bienvenido " + nombre;
        }
        public string saludoNombreApellido(string nombre,string apellido)
        {
            return "Bienvenido " + nombre+" "+apellido;
        }
        public int numeroentero()
        {
            return 10;
        }
        public double numerodecimal()
        {
            return 5.6;
        }

        public List<TipoMedicamentoCLS> listarTipoMedicamento()
        {
            TipoMedicamentoBL obj = new TipoMedicamentoBL();
            return obj.listarTipoMedicamento();
        }
        //Ejemplo sepas leer lo que ponemos en el appsettings.json
        public string cadena()
        {

            IConfigurationBuilder builder = new ConfigurationBuilder();
            builder.AddJsonFile(Path.Combine(Directory.GetCurrentDirectory(), "appsettings.json"));
            var root = builder.Build();
            var cadenaDato = root.GetConnectionString("cn");
            return cadenaDato;
           
        }

        public TipoMedicamentoCLS recuperarTipomedicamento(int iidtipomedicamento)
        {
            TipoMedicamentoBL obj = new TipoMedicamentoBL();
            return obj.recuperarTipoMedicamento(iidtipomedicamento);
        }

        public List<TipoMedicamentoCLS> filtrarTipoMedicamento(string nombretipo)
        {
            TipoMedicamentoBL obj = new TipoMedicamentoBL();
            return obj.filtrarTipoMedicamento(nombretipo);
        }
        //entero (texto)
        public int GuardarDatos(TipoMedicamentoCLS oTipoMedicamentoCLS)
        {
            TipoMedicamentoBL obj = new TipoMedicamentoBL();
            if(oTipoMedicamentoCLS.iidtipomedicamento==0)
            return obj.guardarTipoMedicamento(oTipoMedicamentoCLS);
            else
            return obj.editarTipoMedicamento(oTipoMedicamentoCLS);
        }

        public int eliminarTipoMedicamento(int id)
        {
            TipoMedicamentoBL obj = new TipoMedicamentoBL();
            return obj.eliminarTipoMedicamento(id);
        }

    }
}

AppNetCodeCapas6/Views/TipoMedicamento/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index Tipo Medicamento</h1>

<fieldset>
    <legend>Datos del Tipo Medicamento</legend>
    <form method="post" id="frmGuardarTipoMedicamento" class="mb-3">
        <div class="row">
            <div class="col-md-6">
                <label>Id Tipo Medicamento</label>
                <input type="text" readonly name="iidtipomedicamento" class="form-control"/>
            </div>
            <div class="col-md-6">
                <label>Nombre</label>
                <input type="text" name="nombre" class="form-control ob max-100 min-5 sl" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label>Descripcion</label>
                <textarea name="descripcion" class="form-control ob max-250 min-20 slcenbn"></textarea>
            </div>
        </div>
    </form>
    <button class="btn btn-primary" onclick="GuardarDatos()">Guardar</button>
    <button class="btn btn-danger" onclick="LimpiarMedicamento()">Limpiar</button>
</fieldset>

<div class="input-group mb-3">
    <input type="text" class="form-control" placeholder="Ingrese Tipo de Medicamento" id="txtnombrebusqueda" onkeyup="filtrarTipoMedicamento()"/>
</div>

<div id="divTabla">
   
</div>

<script src="~/js/sweetalert.js"></script>
<script src="~/js/generic.js"></script>
<script src="~/js/tipomedicamento.js"></script>

AppNetCodeCapas6/Views/TipoMedicamento/Inicio.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<h1>Inicio</h1>

<div id="divTabla">

</div>

<script src="~/js/generic.js"></script>
<script src="~/js/tipomedicamento.js"></script>

AppNetCodeCapas6/Views/TipoMedicamento/SinMenu.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SinMenu</title>
</head>
<body>
    <h1>Sin Menu</h1>
    <a class="nav-link text-dark" asp-area="" asp-controller="TipoMedicamento" asp-action="Index">Index</a>
</body>
</html>